version: '3.7'

services:
    emby:
        build: 
            context: .
            target: dev
        volumes:
            - /data/video-streaming/config:/config # Configuration directory
            - /data/video-streaming/video:/mnt/video # Media directory
        networks:
            - nginxproxygitdeploy_net-proxy
        restart: unless-stopped

networks:
    nginxproxygitdeploy_net-proxy:
        external: true