version: "3.7"

services:
  emby:
    image: emby/embyserver
    environment:
        - VIRTUAL_HOST=video.fenrir.ovh
        - VIRTUAL_PORT=8096
        - LETSENCRYPT_HOST=video.fenrir.ovh
        - LETSENCRYPT_EMAIL=contact@alexismartial.fr
    volumes:
      - /data/video-streaming/config:/config # Configuration directory
      - /data/video-streaming/video:/mnt/video # Media directory
    restart: unless-stopped
    networks:
        - nginxproxygitdeploy_net-proxy

networks:
    nginxproxygitdeploy_net-proxy:
        external: true
